# on push to master:
#   - bumps npm version number, see: https://github.com/marketplace/actions/automated-version-bump
#   - creates new github tag
#   - publishes npm package

name: publish npm package

on:
  push:
    branches:
      - feature/auto-npm-publishing

jobs:  
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: 'phips28/gh-action-bump-version@master'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{ secrets.github_token }}
